name: Deploy Dev

on:
  push:
    branches:
      - development

jobs:
  build-and-test:
    name: Build and Test
    runs-on:
      ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0
      
      - name: Install dependencies
        run: dotnet restore backend/developer-store-backend.sln

      - name: Project build
        run: dotnet build --no-restore --verbosity normal

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal
  
  create-pr:
    name: Open Pull Request to Homolog
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with: 
          branch: development
          base: homolog
          title: "Sync: development to homolog"
          body: "Automated pull request to sync changes from development to homolog"
    